language: r
r: bioc-release
cache:
  packages: true
bioc_check: true
warnings_are_errors: false
r_build_args: --no-build-vignettes
r_check_args: --no-build-vignettes
r_packages:
  - covr
os:
  - linux
  - osx
r_packages:
  - igraph
  - readr
  - dplyr
  - stringr
after_success:
  - Rscript -e 'covr::codecov()'
notifications:
  email:
    recipients:
	- ivanovaos.09@gmail.com
    on_failure: always
